# Generated by Django 3.1.7 on 2021-04-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='category',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
