# Generated by Django 3.1.7 on 2021-04-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0002_auto_20210401_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
