# Generated by Django 3.1.7 on 2021-04-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0003_pet_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
