# Generated by Django 3.1.7 on 2021-04-01 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0005_auto_20210401_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
