# Generated by Django 3.1.7 on 2021-04-01 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetPhotos', '0006_auto_20210401_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='about_pet',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='images')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetPhotos.category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
