# Generated by Django 3.1.7 on 2021-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0007_auto_20210401_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to=None),
        ),
    ]
