# Generated by Django 3.1.7 on 2021-04-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0012_auto_20210402_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
