# Generated by Django 3.1.7 on 2021-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0013_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
