# Generated by Django 3.1.7 on 2021-04-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0016_auto_20210403_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
