# Generated by Django 3.1.7 on 2021-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0017_auto_20210403_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='about_pet',
            field=models.CharField(default='', max_length=300),
        ),
    ]
