# Generated by Django 3.1.7 on 2021-04-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0018_auto_20210403_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='about_pet',
        ),
    ]
