# Generated by Django 3.1.7 on 2021-04-04 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetPhotos', '0023_auto_20210404_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='likes',
            field=models.ManyToManyField(related_name='like_count', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
