# Generated by Django 3.1.7 on 2021-04-04 17:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PetPhotos', '0024_auto_20210404_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='likes',
            field=models.ManyToManyField(related_name='picture_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
