# Generated by Django 3.1.7 on 2021-04-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetPhotos', '0028_auto_20210404_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetPhotos.picture'),
        ),
    ]
